language: ruby
rvm: 
  - "2.1.1"
gemfile: Gemfile
before_script: mkdir ~/.aws && touch ~/.aws/helga_candys.yml &&  echo 'access_key_id: ENV["AWS_ACCESS_KEY"]\naccess_key_secret: ENV["AWS_SECRET"]' >> ~/.aws/helga_candys.yml
script: bundle exec rake mm:publish 
deploy:
  - provider: s3
    access_key_id: <%= ENV["AWS_KEY_ID"] %>
    secret_access_key: <%= ENV["AWS_SECRET"] %>
    region: 'eu-central-1'
    revision_type: github
    bucket: "helgacandys"
    application: helga_candys
